@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.subtle_effects.client.model.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;