# Project
version=1.15.0-hotfix.1
group=einstein.subtle_effects
java_version=25

# Common
loom_version=1.18-SNAPSHOT
moddev_version=2.0.147
minecraft_version=26.3
max_minecraft_version=26.4
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1
fzzy_config_version=0.7.7+26.3
glitchcore_version=1.21.11-21.11.0.3
serene_seasons_version=26.1.1-26.1.1.0.1
cobweb_version=26.1-1.4.0
prometheus_version=26.1-1.2.5
puzzleslib_version=26.3.12
multiloaderdataextensions_version=26.1.0
mixin_constraints_version=1.1.0

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.19.5
fabric_api_version=0.160.5+26.3
modmenu_version=21.0.0
fabric_iceberg_version=8w9heVpo
fabric_prism_version=hIejSxjq
fabric_item_borders_version=yZWXg0WM
fabric_endrem_version=NcYD9vWQ
fabric_sodium_version=VTidoe6U
fabric_iris_version=1.11.7+26.3-fabric
fabric_dyed_flames_version=sG4bXNnZ

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.3.0.48-beta
neoforge_loader_version_range=[4,)
neoforge_iceberg_version=18BLvCZh
neoforge_prism_version=NYnrLePp
neoforge_item_borders_version=WjErgKWV
neoforge_endrem_version=wAzVI0hr
neoforge_sodium_version=ihzX2Dvy
neoforge_iris_version=1.11.7+26.3-neoforge
neoforge_dyed_flames_version=sG4bXNnZ
neoforge_better_modlist=LJPYSNL2

# Mod options
mod_name=SubtleEffects
mod_author=MincraftEinstein
mod_id=subtle_effects
description=Adding many new subtle details through particles and a few sounds

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
