@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.ambient_sleep.client.particle.option;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;