@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.subtle_effects.client.renderer.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;