@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.ambient_sleep.client.particle.provider;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;