@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.subtle_effects.networking.clientbound;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;