@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.subtle_effects.particle.option;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;