@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package einstein.ambient_sleep.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;